/**
Gentle app definition.

Modules are registered here, along with their positioning in the layout.

The app is stored in `window.gentle` for global access.

@class App
@extends EventEmitter, Gentle
**/

require([
    'views/layout',
    'domReady',
    'models/sequence',
    'models/sequences',
    'views/sequence_view',
    'router',
    'backbone',
    'gentle',
    'bootstrap',
  ], function(Layout, domReady, Sequence, Sequences, SequenceView, Router, Backbone, Gentle) {

  Gentle = Gentle();

  Gentle.sequences = new Sequences();

  Gentle.sequences.fetch();

  // Gentle.sequences.add({
  //   id: 1,
  //   name: 'blablabla',
  //   sequence: 'ATCGAT'
  // });
  
  // Gentle.sequences.add({
  //   id: 2,
  //   name: 'blablabla',
  //   sequence: 'ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG'
  // });

  // Gentle.currentSequence = Gentle.sequences.last();

  Gentle.router = new Router();

  domReady(function() {
    Gentle.layout = new Layout();
    Backbone.history.start();
  });
});